name: Run linters
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup
              uses: actions/setup-node@v2
              with:
                  node-version: "16.6.0"
            - name: Install
              run: npm i --legacy-peer-deps
            - name: Lint
              run: npm run lint
